packages:
  - apps/*
  - packages/*

patchedDependencies:
  fast-png@^8.0.0: patches/fast-png.patch

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - browser-tabs-lock
  - core-js
  - esbuild
  - llama.rn
